name: SRT YF

on:
  schedule:
    - cron: '20 10 * * *'  # 3:50 PM IST = 10:20 UTC
  workflow_dispatch:

jobs:
  run-strategy:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas yfinance ta requests

      - name: Run Strategy Script
        run: python nifty200_screenery_yfinance.py
