name: Run SST

on:
  schedule:
    - cron: '20 10 * * *'  # 3:50 PM IST = 10:20 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas requests ta gspread oauth2client pytz

      - name: Run the Screener Script
        env:
          GCP_CREDS_JSON: ${{ secrets.GCP_CREDS_JSON }}
        run: |
          echo "$GCP_CREDS_JSON" > credentials.json
          python screener.py
